# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# Pipeline that checks branches that have been pushed to "Main" OR are the source branch in a newly created pull request into "Main"
# Fails the test if there are Python syntax errors or undefined names OR pytest fails

name: HCC dashboard Pylint and tests Validation

on:
  push:
    branches: [test-pipeline]
  pull_request:
    branches: [test-pipeline]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: [1.1.12]
        # os: [ubuntu-20.04, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python modules
        run: |
          pip install --upgrade pip
          pip install -r reqs.txt
          pip install -r reqs-dev.txt
      - name: Lint with Pylint
        run: |
          pylint hcc_dashboard/hcc_dashboard
          pylint hcc_dashboard/hcc
      - name: Tests validation
        run: |
          python hcc_dashboard/manage.py test hcc_dashboard.hcc.tests
